version: "3.5"
services:
    minipress:
      container_name: minipress
      image: minipress:latest
      restart: always
      user: root
      environment:
        # 设置时区环境变量
        - 'SET_CONTAINER_TIMEZONE=true'
        - 'CONTAINER_TIMEZONE=Asia/Shanghai'
      volumes:
        # 同步宿主机时间
        - /etc/localtime:/etc/localtime
        # 挂载头像上传目录
        - /flask/upload/icon:/opt/python/flask/minipress/static/upload/icon
        # 挂载相册上传目录
        - /flask/upload/photo:/opt/python/flask/minipress/static/upload/photo
      ports:
        - "5000:5000"
      networks:
        - app_minipress

networks:
  app_minipress:
