version: "3.5"
services:
    minipress:
      container_name: minipress
      image: minipress:latest
      restart: always
      user: root
      volumes:
      - /etc/localtime:/etc/localtime
      - /flask/upload/icon:/opt/python/flask/minipress/static/upload/icon
      - /flask/upload/photo:/opt/python/flask/minipress/static/upload/photo
      ports:
      - "5000:5000"
      networks:
      - app_minipress

networks:
  app_minipress:
