version: "3.5"
services:
    minipress:
      container_name: minipress
      image: minipress:latest
      restart: always
      user: root
      volumes:
      - "/etc/localtime:/etc/localtime"
      ports:
      - "5000:5000"
      networks:
      - app_minipress

networks:
  app_minipress:
